### ISSUE TITLE
roadmap for v4

### ISSUE THREAD

**Issue by jbasko** [jbasko/wr-profiles#2]
v5.x
====

* [ ] Remove `to_envvars` -- `create_env` returns an `Environment` with much more flexibility.

v4.x
======

* [ ] Clean up tests: remove duplication.
* [ ] Document const values and defaults features.

v4.1.0
======

* [x] Fix `envvar_profile()` return type annotation, should be `EnvvarProfile`, not `Type[EnvvarProfile]`.

v4.0.0
======

* [x] String values only. No serialisers, no deserialisers.
* [x] No default values. None means value not set.
* [x] Inherits `collections.abc.Mapping` so you can do `dict(**profile)`
* [x] `list(profile)` returns names of all properties
* [x] ability to create one without an explicit class declaration
